<h2>Recent Articles</h2>
<section id="recent-articles" class="articles">

<?php
foreach ($articles as $article):
    $topic = $article->getTopic();
    $classes = ['light', 'topic-'.$topic->slug];

    if ($article->featured === TRUE):
        $classes[] = 'featured';
    endif; ?>

    <article class="<?php echo implode( ' ', $classes ); ?>">
        <h3>
            <a href="<?php echo $article->url; ?>"><?php echo $article->title; ?></a>
            <span class="topic-<?php echo $topic->slug; ?> topic-<?php echo $topic->slug; ?>-text badge"><?php echo $topic->label; ?></span>
        </h3>
        <blockquote>
            <em class="date"><?php echo $article->dateString('j F Y'); ?></em>
            <span>&mdash;</span>
            <span class="snippet"><?php echo $article->snippet; ?></span>
        </blockquote>
    </article>

<?php
endforeach;

if (! $articles): ?>

<div class="no-results">No articles yet</div>

<?php
endif; ?>