<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?php echo $title; ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <base href="<?php echo $basepath; ?>">

        <link rel="icon" href="<?php echo $basepath; ?>/favicon.ico">

        <link rel="stylesheet" href="css/fonts.css">
        <link rel="stylesheet" href="css/site.css">
        <link rel="stylesheet" href="css/media.css">

        <style type="text/css">
        <?php
        foreach ($topics as $slug => $topic):
            echo sprintf(".topic-%s { background-color: rgb(%s); }\n", $slug, $topic->rgb());
            echo sprintf(".topic-%s-text { color: rgb(%s); }\n", $slug, $topic->rgb(3));
            echo sprintf(".topic-%s-text:visited { color: rgb(%s); }\n", $slug, $topic->rgb(3));
            echo sprintf(".topic-%s.light { background-color: rgba(%s); }\n", $slug, $topic->rgba());
            echo sprintf(".topic-%s.lighter { background-color: rgba(%s); }\n", $slug, $topic->rgba(2));
            echo sprintf(".topic-%s-border { border-color: rgb(%s); }\n", $slug, $topic->rgb());
            echo sprintf(".topic-%s-border.light-border { border-color: rgba(%s); }\n", $slug, $topic->rgba());
        endforeach;
            echo $css; ?>
        </style>
    </head>
    <body class="<?php echo $page; ?><?php echo $theme ? ' theme-'.$theme : ''; ?>">
        <header class="group">
            <nav class="logo group">
                <a href="<?php echo $homeUrl; ?>">
                    <span class="brand"><?php echo $logo; ?></span>
                    <span class="name"><?php echo nl2br( $logoTagline ); ?></span>
                </a>
            </nav>
            <section class="subtitle">
                <span class="larger"><?php echo $subtitle; ?></span><br>
                <span class="smaller"><?php echo $subtitleTagline; ?></span>
            </section>
            <nav class="menu group">
                <a class="button sitemap" href="<?php echo $sitemapUrl; ?>">
                    <span>Sitemap</span>
                </a>
            </nav>
        </header>
        <main class="group">
            <nav class="sidebar">
                <?php echo render(TPL_CONTRIBUTORS, ['contributors' => $contributors]); ?>
            </nav>
            <section class="content">
                <?php echo $content; ?>
            </section>
            <section class="topics">
                <h2>Topics</h2>
            <?php
            if ($topics): ?>
                <ul>
                <?php
                foreach ($topics as $topic): ?>
                    <li class="topic">
                        <a href="<?php echo $topic->url; ?>" class="topic-<?php echo $topic->slug; ?> topic-<?php echo $topic->slug; ?>-text">
                            <span class="label"><?php echo $topic->label; ?></span>
                            <span class="count"><?php echo $topic->count; ?></span>
                        </a>
                    </li>
                <?php
                endforeach; ?>
                </ul>
            <?php
            else: ?>
                <div class="no-results">No topics yet</div>
            <?php
            endif; ?>
            </section>
            <section class="contributors">
                <?php echo render(TPL_CONTRIBUTORS, ['contributors' => $contributors]); ?>
            </section>
        </main>
    </body>
</html>