<section id="topic" class="topic">
    <h1>
        <span class="topic-<?php echo $topic->slug; ?> topic-<?php echo $topic->slug; ?>-text">
            <?php echo $topic->label; ?>
        </span>
    </h1>

<?php
foreach ($articles as $article):
    $classes = [
        //'light-border',
        'topic-neutral',
        'topic-'.$topic->slug.'-border'
    ]; ?>

    <article class="<?php echo implode(' ', $classes); ?>">
        <h3>
            <a href="<?php echo $article->url; ?>"><?php echo $article->title; ?></a>
        </h3>
        <blockquote>
            <em class="date"><?php echo $article->dateString('j F Y'); ?></em>
            <span>&mdash;</span>
            <span class="snippet"><?php echo $article->snippet; ?></span>
        </blockquote>
    </article>

<?php
endforeach;

if (! $articles): ?>

    <div class="no-results">No articles yet</div>

<?php
endif; ?>

</section>