<aside>
    This article is the second in a
    <a href="<?php echo $article->getTopic()->url; ?>">series</a>
    on Privacy and Security.
</aside>

<p>
    If you were the only person on the Earth, there would be no need for
    privacy. You would have nothing to keep private and no one to keep
    anything private from. This changes when you meet someone &ndash;
    you now have a new entity with whom you may want to withhold
    information. You now have your “personal life”, the internal
    thoughts and feelings that you keep to yourself, and your “public
    life”, the external thoughts and words that you project to the other
    person. “Personal” and “Public” are the first two “spheres” in our
    modeling of privacy in our lives.
</p>

<!--
<img alt="Image of personal sphere next to public sphere, arrows labeling each.
    Depicting personal information as separate from public information]" />
-->

<blockquote>
    <b>Privacy Spheres</b> are the different <i>domains</i> that
    information is classified or categorized under. Information moves
    between spheres via <i>channels</i>.
</blockquote>

<p>
    As we add more people this model becomes more complicated. We have
    families, friends, and different groups of friends that we’ve met at
    various stages in our lives. We have jobs, co-workers, and bosses.
    We have girlfriends, boyfriends, wives, husbands, sexual partners,
    and more. The list can be wildly complicated for some people, and
    very short and modest for others. However, the entire network of
    connections can be reduced to a manageable set of six different
    spheres:
</p>

<ol>
    <li>Personal</li>
    <li>Private</li>
    <li>Family</li>
    <li>Social</li>
    <li>Professional</li>
    <li>Public</li>
</ol>

<p>
    These six spheres can be thought of as your different “lives” or
    “selves” &ndash; your “Private Sphere” can be thought of as your
    “Private Life”; your “Social Sphere” as your “Social Life”, etc.
    <b>Privacy is the management of your information across these
    spheres.</b> It’s important to note that the content of the information
    need not matter and that it’s up to the individual to determine which
    pieces of information to hide and from whom. We won’t concern ourselves
    with <i>why</i> that information is hidden, or even what that
    information is. Those two questions are irrelevant here 😜
</p>

<h3 id="personal">Personal Sphere</h3>

<p>
    The words “personal” and “private” can mean different things
    depending on who you ask. Here, “personal” means “you”: the life
    <i>you</i> live that is known only to you and no one else. This is
    information that you don’t normally share with anyone, not even your
    husband, wife, father, mother, etc. For some people, this sphere is
    tiny or nonexistent, and for others it can be the most dominant sphere
    in their lives.
</p>
<p>
    The Personal Sphere can encompass spiritual beliefs that you practice on
    your own, or your thoughts and feelings while you meditate. It can be
    your conversations with yourself, or dreams and wishes that you have. It
    can be the bucket list you keep in a lockbox under your bed. Some people
    let others into the personal areas of the life, while other people keep
    this to themselves for their entire lives. As we’ll see, personal
    information that is shared to others is no longer personal. You can ask
    the other person to keep it secret, but the decision to honor that will
    always be theirs.
</p>

<h3 id="private">Private Sphere</h3>

<p>
    The Private Sphere refers to your romantic or sexual life. This is
    information, thoughts, feelings, desires, and preferences that you
    maintain regarding your sexuality. It can be the most heavily guarded
    sphere of our lives, and when information leaks from this sphere it can
    cause cataclysmic reactions and repercussions elsewhere. Just think of
    any political or professional scandal where someone in power stepped
    down after a picture or video was released, exposing an act from their
    private life. There are too many to count!
</p>
<p>
    Some people behave very differently when they’re alone with their
    significant other or sexual partner. They may say or do things that they
    would never want someone else to know. We are now entering the thick of
    the forest in understanding privacy, and it is here that we may better
    understand privacy as both a “balance” and a “spectrum”: the
    <i>balance</i> would be very much upset if someone or certain people
    were to see this private side of us; where we fall on the operations
    security <i>spectrum</i> changes based on what we have at stake to lose.
</p>

<h3 id="family-social-professional">
    Family, Social, and Professional Spheres
</h3>

<p>
    It can be difficult to distinguish between the Family and Social
    spheres. For some, these are the same, and for others they may be very
    different. As an example, imagine a friend having cancer and only
    telling her family members. For some reason, your friend wants this
    information to stay “in the family”. Another example is a teenager who
    tells their friends things that they don’t want their siblings or
    parents to know about.
</p>
<p>
    There is often much overlap between the family and social spheres, but
    they are distinguished enough to separate in our model. When thinking
    about your own privacy, it’s wise to think about these two separately.
    Problems can arise when they’re assumed to be the same. This isn't to
    say non-relatives can't be included in the Family Sphere, just that the
    two spheres are different enough to consider separately.
</p>
<p>
    Our professional life is who we are in the workplace. It’s our
    coworkers, bosses, interns; it’s the people we work with and what we
    project occupationally. There are many examples where leaked information
    has an adverse side-effect on that person’s professional life. Countless
    people have lost jobs over things they posted on the Internet. Countless
    people have also lost their jobs after bringing their private or family
    life into the workplace. The professional sphere is one that almost
    everyone relies on for their livelihood and one that can have the most
    impact depending on how it’s managed.
</p>

<h3 id="public">Public Sphere</h3>

<p>
    The public sphere is the most complex. It’s who we are to the outside
    world; the persona we project to those that do and do not know us; the
    information about us that is available to others whether they’re looking
    for it or not. Celebrities have a more larger public presence, and a
    totally different set of problems to solve than, say, a suburban
    teenager. However, both possess a public life and the problems it can
    bring. It’s easier for our public lives to both impact and become
    impacted by other areas of our life. When things from our private life
    are exposed to the public, it can be catastrophic. When we do negative
    or harmful things publicly, those actions can harm our family, social,
    business, or romantic relationships.
</p>
<p>
    Additionally, we may be sharing our private data “publicly” without even
    knowing it. (This topic is known as operations security<sup>1</sup>.)
    For example, consider your credit card purchases. At first, this data
    appears private: only the credit card company knows what you’re buying.
    However, you’re also sharing this data with unknown people who work
    there. You’re sharing it with any third party that the credit card
    company chooses to share it with, as laid out in their terms of service
    that you agreed to. These third parties could have anonymized data, or
    they could have your name and contact info; they themselves could be
    further sharing your data with yet more companies. Furthermore, any of
    these companies could be storing your data poorly, thus opening
    themselves to having your data stolen by unknown criminals. Is it public
    or private?
</p>
<p>
    The answer is unsurprisingly “both”. It’s private from the population
    at-large, yet it’s available to any willing bad actor with means and
    motivation. The credit card company goes to great lengths to protect the
    information from the general population, but an ex-partner who has it
    out for you could get a job there and locate your transaction history.
    This should reinforce the notion that privacy exists on a spectrum, and
    that managing our privacy involves making tradeoffs and adapting to your
    environment. In this instance, perhaps the solution isn’t to ditch the
    credit card, but to use cash for sensitive transactions.
</p>
<p>
    When it comes to privacy, not only are there six discreet lives we live
    in and manage, but these lives, or spheres, can “overlap” in many
    different ways. This overlap in the real world is what contributes to
    the potential imbalance of privacy in our lives.
</p>

<h3 id="info-overlap">Information Overlap</h3>

<p>
    The entire reason why privacy issues arise is because information has a
    tendency to go where we don’t want it to go. In the theoretical world,
    we can define exactly what we want to share and with whom, and then
    we’re done. However, in the real world, tradeoffs are made for
    convenience; or there are bad actors who are looking to exploit
    information for their own gain; or we forget things we’ve done in the
    past; or we were carless or ignorant of what information we’ve granted
    access to and to whom. This list goes on and on and it contributes to
    the increasing overlap of information across spheres.
</p>
<p>
    When information overlaps in a way that we don’t feel comfortable,
    regardless of whether we know about it or not, an <b>imbalance</b> is
    created in our privacy system. This imbalance can manifest itself in
    different ways, depending on how much it matters to us. At a base level,
    if we don’t care that information is leaking, then none of this matters.
    If details of your recent divorce are made public and you don’t care,
    then there’s no cause for alarm. Assuming that we <i>do</i> care, the
    imbalance can cause us to feel sick, violated, uneasy, worried, or
    scared. Perhaps you wanted some details of the divorce to stay private
    between you and your partner (Private Sphere), and now having your
    children (Family Sphere) aware of them causes harm to your family’s
    well-being.
</p>
<p>
    Once information is leaked it may never go back to how it was before.
    The fear of losing innocence or respect can compound our worries and
    unease. All of this manifests itself as discontent, and it’s caused by
    the lack of balance in the information we’re sharing, what we feel
    comfortable sharing, and with whom we share it with.
</p>

<h3 id="privacy-balance">Privacy as a Balance</h3>

<p>
    We can think of privacy as a balancing act between these three things:
    what we share, what of that we feel comfortable sharing, and with whom
    we share it with. The greater the balance, the better and more confident
    we feel. The greater the imbalance, the worse and more uncomfortable we
    feel. Practicing privacy then becomes learning how to maintain this
    balance. To maintain the balance, we must first identify these three
    factors across all six spheres in our lives. We know what an imbalance
    can look like &ndash; pictures from your private life are leaked on the
    Internet causing chaos in your life &ndash; but what does a good balance
    look like?
</p>
<p>
    This is a difficult question to answer, because good privacy is usually,
    and unfortunately, defined by what it’s <i>not</i>. It’s not having your
    identity stolen, or not having your confidential information used
    against you. It can even look like, as we’ll soon see, not having your
    mother always asking you to call her more. These are easy to think of,
    but what are some positive examples? A good balance looks a lot like
    having good self-awareness. It looks like someone who has their life
    together, or rarely seems overwhelmed. It looks like someone who is
    usually in a good mood, or who has good relationships with their
    friends, family, and co-workers. This balance comes from being in tune
    with yourself, the relationships in your life, and what you’re doing and
    not doing with your information and data.
</p>
<p>
    To achieve this you must first identify what you’re sharing and not
    sharing. This process may be the most eye-opening and difficult part of
    all. You then determine which of that information you want to share and
    to which areas of your life (or people) you want to share it with. This
    is often already known to you, whether you’ve done the exercise or not,
    but can be very helpful to think through and write it down or see it on
    paper. These two steps are critical for practicing and exercising strong
    privacy in our lives.
</p>

<h3>Practicing and Exercising</h3>

<p>
    Achieving a good privacy balance is not difficult, and can be done by
    anyone willing. The following exercises can be done in minutes or
    hours depending on your desire, but the benefits can be realized
    immediately. To start, you need to take inventory of what information
    you are and are not sharing to the various spheres in your life. It’s
    important to note, now, that having a good balance is not only about
    removing or hiding things from others, but it also can involve realizing
    areas where we’re <i>under-sharing</i> information to the detriment of
    our relationship with that person or those persons. Consider the
    previous example of your mother always asking you to call her more
    frequently. There’s a good chance she’s asking because she feels she
    isn’t getting enough insight into your life. You may decide that you’re
    giving as much as you want, but it’s important to realize that giving
    more information to certain people we care about can help make the
    relationship stronger, thus improving our well-being.
</p>
<p>
    These next two exercises can be done quickly and easily, but can require
    much introspection to do fully. I’ve put together a 15-minute quiz that
    asks you many different questions, and prepares a list of action items
    based on your own privacy preferences:
</p>

<p>[TBD] -- [Take the 15-minute Privacy Quiz]</p>




<h3>References</h3>

<ol id="appendix">
    <li>
        <a href="<?php $wl('opsec'); ?>">Operations Security</a>,
        <i>Wikipedia</i>
    </li>
</ol>